export enum SessionTypes {
  SESSION_RETRIEVE_REQUEST = '@@session/RETRIEVE_REQUEST',
  SESSION_RETRIEVE_SUCCESS = '@@session/RETRIEVE_SUCCESS',
  SESSION_RETRIEVE_FAILED = '@@session/RETRIEVE_FAILED',
}
